
name: "road_vision"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mqtt_network
    restart: unless-stopped

  fake_agent:
    container_name: agent
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      DELAY: 0.1
    networks:
      - mqtt_network
    restart: on-failure

networks:
  mqtt_network:
    driver: bridge


